version: '3.7'

services: 
  database:
    image: postgres:10.1-alpine
    volumes: 
      - postgres_data:/var/lib/postgresql/data/
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_DB=proxybackend
      
  backend:
    build: . 
    command:  python /usr/src/backend/manage.py runserver 0.0.0.0:5000
    volumes: 
      - ./proxysite/:/usr/src/backend/
    ports: 
      - 5000:5000
    env_file:
      - ./.env.dev
    depends_on: 
      - database  
      
  frontend:
    build: ../frontend/client
    volumes: 
      - ../frontend/client:/app
      - /app/node_modules
    ports: 
      - 8080:8080    
volumes: 
  postgres_data: