version: '3.7'

services:
  database:
    image: postgres:10.1-alpine
    volumes: 
      - postgres_data:/var/lib/postgresql/data/
    env_file: 
      - ./.env.db.prod
  backend:
    build: 
      dockerfile: Dockerfile.prod
      context: .
    command: gunicorn proxysite.wsgi --bind 0.0.0.0:8000
    # command: /bin/bash
    volumes:
      - static_volume:/usr/src/backend/staticfiles/
    ports: 
      - 8000:8000
    env_file: 
      - ./.env.prod
    depends_on:
      - database  
  
  nginx:
    build: 
      dockerfile: ./backend/nginx/Dockerfile
      context: ../
    ports: 
      - 80:80
    volumes:
      - static_volume:/usr/src/backend/staticfiles/
    depends_on: 
      - backend
      - database
 

  
volumes:
  postgres_data:
  static_volume:
