# Generated by Django 3.1.6 on 2021-02-21 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxylist',
            name='ping_to_google',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='proxylist',
            name='ping_to_yandex',
            field=models.FloatField(),
        ),
    ]
