# Generated by Django 3.1.6 on 2021-02-21 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210221_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxylist',
            name='proxyType',
            field=models.CharField(choices=[('http', 'HTTP'), ('https', 'HTTPS'), ('socks5', 'SOCKS5'), ('socks4', 'SOCKS4')], max_length=100),
        ),
    ]
